# Run tasks with: plz [taskname]
# Docs: https://plzplz.org/reference.html
# Show the schema for this file: plz plz schema

# Faster way to check for errors
[tasks.check]
run = "cargo check"

# Run, development mode
[tasks.dev]
run = "cargo run"

# Small population
[taskgroup.run.default]
run = "cargo run --release -- --params params/default.toml"

# 10 million people
[taskgroup.run.large]
run = "cargo run --release -- --params params/large_pop.toml"

# Build, development mode
[tasks.build]
run = "cargo build"

# Run tests
[tasks.test]
run = "cargo test"
git_hook = "pre-push"

# Check linting and formatting
[tasks.lint]
run_serial = ["cargo clippy", "cargo fmt --check"]
fail_hook = { suggest_command = "plz fix" }
git_hook = "pre-commit"

# Fix lint and formatting issues
[tasks.fix]
run_serial = ["cargo fmt", "cargo clippy --fix --allow-dirty"]

# Build, release mode
[tasks.release]
run = "cargo build --release"

[taskgroup.ui.extends]
env = "pnpm"
dir = "simulator"

# Start development server
[taskgroup.ui.setup]
run = "pnpm install"


# Start development server
[taskgroup.ui.dev]
depends = ["ui.setup"]
run = "vite"

# Build for production
[taskgroup.ui.build]
depends = ["ui.setup"]
run = "vite build"
git_hook = "pre-push"

# Preview production build
[taskgroup.ui.preview]
depends = ["ui.setup"]
run = "vite preview"
